### PR TITLE
Filter imported dfns from extracted dfns

### LINKED ISSUE #1092: Adjust dfn extraction for the HTML spec
Looking at remaining custom code for extracting dfns from the HTML spec, I notice that we have:

https://github.com/w3c/reffy/blob/b1a154f03a8ccb74e87b1494158c599d37b4c79d/src/browserlib/extract-dfns.mjs#L597-L604

But the [`style` attribute dfn in HTML](https://html.spec.whatwg.org/multipage/infrastructure.html#dom-style) is an imported definition from CSSOM, and we ignore (in theory, see below) other such definitions. Why keep this one?

https://github.com/w3c/reffy/blob/b1a154f03a8ccb74e87b1494158c599d37b4c79d/src/browserlib/extract-dfns.mjs#L606-L610

That's meant to exclude imported definitions... but it does nothing in practice so that needs fixing.
Other specs probably use the same pattern as well. Worth generalizing the rule?

https://github.com/w3c/reffy/blob/b1a154f03a8ccb74e87b1494158c599d37b4c79d/src/browserlib/extract-dfns.mjs#L587-L593

That excludes definitions in the Index page... but events are defined there. Shouldn't we now try to parse the page?

### PR DESCRIPTION
**Pull request by tidoust**
Various specs import definitions from other specs. Such "proxy" definitions are not real definitions. This update makes the extraction logic skip them.

This update also drops useless pre-processing logic for the HTML spec, see #1092 for details.

This will remove a number of (ghost) private definitions from the extracts, including over 1250 definitions from HTML.

Examples of spec sections that use imported dfns:
https://html.spec.whatwg.org/multipage/infrastructure.html#dependencies https://html.spec.whatwg.org/multipage/parsing.html#character-encodings https://drafts.csswg.org/web-animations-2/#grouping-and-synchronization https://w3c.github.io/web-share-target/#dom-webappmanifest https://wicg.github.io/js-self-profiling/#profiling-sessions https://w3c.github.io/webdriver/#index
https://w3c.github.io/DOM-Parsing/#dependencies
https://w3c.github.io/json-ld-framing/#terms-imported-from-other-specifications https://w3c.github.io/network-error-logging/#dependencies https://w3c.github.io/payment-handler/#dependencies https://w3c.github.io/dnt/drafts/tracking-dnt.html#terminology

Examples of specs that use imported dfns, but that could be worth fixing because nothing links back to the local definition in practice, as all references target the external spec directly:
https://wicg.github.io/is-input-pending/
https://wicg.github.io/netinfo/#navigatornetworkinformation-interface

This fixes #1092.

### CODE REVIEW

**Comment by tidoust** [comment]
CI tests fail with an internal error. That seems to be related with the deprecation of Ubuntu 18.04.

**Review by dontcallmedom — APPROVED** [review]
The code LGTM in the abstract

> This will remove a number of (ghost) private definitions from the extracts, including over 1250 definitions from HTML.

How confident do you feel about the assessment these definitions are indeed ghost ones? e.g. have you a chance to check they're all private definitions or if any of them are being linked x-specs via xref?

**Comment by tidoust** [comment]
Here is the full list of imported dfns that this would filter and that are public. Basically all of them are in CSS specs and are public by virtue of being of type `value`. I don't think they are referenced by other specs. If they are, I think we need to act on that and this list will give us the IDs to track (nothing should break in the meantime, CSS specs use Shepherd's xref database for now).

10 definitions have a `dfn` type but they don't seem to be referenced by any other spec in any case.

Public dfns with a `value` type:
- [`<dashed-ident>`](https://drafts.csswg.org/css-anchor-1/#valdef-anchor-name-dashed-ident)
- [`<dashed-ident>`](https://drafts.csswg.org/css-anchor-1/#valdef-position-fallback-dashed-ident)
- [`<box>`](https://drafts.csswg.org/css-backgrounds-4/#valdef-background-clip-box)
- [`<integer [1,∞]>`](https://drafts.csswg.org/css-multicol-2/#valdef-column-span-integer-1)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-scroll-snap-2/#valdef-scroll-start-length-percentage-0)
- [`<basic-shape>`](https://drafts.csswg.org/css-shapes-2/#valdef-shape-inside-basic-shape)
- [`<url>`](https://drafts.csswg.org/css-shapes-2/#valdef-shape-inside-url)
- [`<custom-ident>`](https://drafts.csswg.org/css-view-transitions-1/#valdef-page-transition-tag-custom-ident)
- [`<length-percentage>`](https://drafts.csswg.org/scroll-animations-1/#valdef-view-timeline-inset-length-percentage)
- [`<time>`](https://drafts.csswg.org/scroll-animations-1/#valdef-animation-delay-start-time)
- [`<time [0s,∞]>`](https://drafts.csswg.org/css-animations-1/#valdef-animation-duration-time-0s)
- [`<number [0,∞]>`](https://drafts.csswg.org/css-animations-1/#valdef-animation-iteration-count-number-0)
- [`<time>`](https://drafts.csswg.org/css-animations-1/#valdef-animation-delay-time)
- [`<percentage>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-background-position-percentage)
- [`<length>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-background-position-length)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-background-size-length-percentage-0)
- [`<percentage [0,∞]>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-border-image-slice-percentage-0)
- [`<number [0,∞]>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-border-image-slice-number-0)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-border-image-width-length-percentage-0)
- [`<number [0,∞]>`](https://drafts.csswg.org/css-backgrounds-3/#valdef-border-image-width-number-0)
- [`<color>`](https://drafts.csswg.org/css-backgrounds-3/#shadow-color)
- [`<custom-ident>`](https://drafts.csswg.org/css-color-adjust-1/#valdef-color-scheme-custom-ident)
- [`<custom-ident>`](https://drafts.csswg.org/css-contain-3/#valdef-container-name-custom-ident)
- [`<string>`](https://drafts.csswg.org/css-content-3/#valdef-content-string)
- [`<image>`](https://drafts.csswg.org/css-content-3/#valdef-content-list-image)
- [`<string>`](https://drafts.csswg.org/css-content-3/#valdef-leader-string)
- [`<integer [1,∞]>`](https://drafts.csswg.org/css-content-3/#valdef-bookmark-level-integer-1)
- [`<integer>`](https://drafts.csswg.org/css-display-3/#valdef-order-integer)
- [`<number>`](https://drafts.csswg.org/css-flexbox-1/#valdef-flex-grow-number)
- [`<number>`](https://drafts.csswg.org/css-flexbox-1/#valdef-flex-shrink-number)
- [`<number>`](https://drafts.csswg.org/css-fonts-5/#valdef-font-size-adjust-number)
- [`<number>`](https://drafts.csswg.org/css-fonts-5/#valdef-font-face-font-size-number)
- [`<percentage>`](https://drafts.csswg.org/css-fonts-5/#valdef-ascent-overridedescriptor-percentage)
- [`<percentage>`](https://drafts.csswg.org/css-fonts-5/#valdef-superscript-position-overridedescriptor-percentage)
- [`<number [1,1000]>`](https://drafts.csswg.org/css-fonts-4/#valdef-font-weight-number-1-1000)
- [`<percentage [0,∞]>`](https://drafts.csswg.org/css-fonts-4/#valdef-font-stretch-percentage-0)
- [`<absolute-size>`](https://drafts.csswg.org/css-fonts-4/#valdef-font-size-absolute-size)
- [`<relative-size>`](https://drafts.csswg.org/css-fonts-4/#valdef-font-size-relative-size)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-fonts-4/#valdef-font-size-length-percentage-0)
- [`<number [0,∞]>`](https://drafts.csswg.org/css-fonts-4/#aspect-ratio-value)
- [`<string>`](https://drafts.csswg.org/css-fonts-4/#font-language-override-string-value)
- [`<position>`](https://drafts.csswg.org/css-images-3/#valdef-radial-gradient-position)
- [`<length-percentage>`](https://drafts.csswg.org/css-grid-2/#valdef-grid-template-columns-length-percentage)
- [`<custom-ident>`](https://drafts.csswg.org/css-grid-2/#grid-placement-slot)
- [`<angle>`](https://drafts.csswg.org/css-images-4/#valdef-conic-gradient-angle)
- [`<position>`](https://drafts.csswg.org/css-images-4/#valdef-conic-gradient-position)
- [`<basic-shape-rect>`](https://drafts.csswg.org/css-images-4/#valdef-object-view-box-basic-shape-rect)
- [`<resolution>`](https://drafts.csswg.org/css-images-4/#valdef-image-resolution-resolution)
- [`<length>`](https://drafts.csswg.org/css-inline-3/#valdef-baseline-shift-length)
- [`<percentage>`](https://drafts.csswg.org/css-inline-3/#valdef-baseline-shift-percentage)
- [`<length>`](https://drafts.csswg.org/css-inline-3/#valdef-line-height-length)
- [`<number>`](https://drafts.csswg.org/css-inline-3/#valdef-line-height-number)
- [`<percentage>`](https://drafts.csswg.org/css-inline-3/#valdef-line-height-percentage)
- [`<number [1,∞]>`](https://drafts.csswg.org/css-inline-3/#valdef-initial-letter-number-1)
- [`<integer [1,∞]>`](https://drafts.csswg.org/css-inline-3/#valdef-initial-letter-integer-1)
- [`<length>`](https://drafts.csswg.org/css-inline-3/#valdef-initial-letter-wrap-length)
- [`<percentage>`](https://drafts.csswg.org/css-inline-3/#valdef-initial-letter-wrap-percentage)
- [`<image>`](https://drafts.csswg.org/css-lists-3/#valdef-list-style-image-image)
- [`<counter-style>`](https://drafts.csswg.org/css-lists-3/#valdef-list-style-type-counter-style)
- [`<string>`](https://drafts.csswg.org/css-lists-3/#valdef-list-style-type-string)
- [`<length [0,∞]>`](https://drafts.csswg.org/css-multicol-1/#valdef-column-width-length-0)
- [`<integer [1,∞]>`](https://drafts.csswg.org/css-multicol-1/#valdef-column-count-integer-1)
- [`<color>`](https://drafts.csswg.org/css-multicol-1/#valdef-column-rule-color-color)
- [`<visual-box>`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip-margin-visual-box)
- [`<length [0,∞]>`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip-margin-length-0)
- [`<string>`](https://drafts.csswg.org/css-overflow-3/#valdef-block-ellipsis-string)
- [`<integer>`](https://drafts.csswg.org/css-overflow-3/#valdef-line-clamp-integer)
- [`<integer>`](https://drafts.csswg.org/css-overflow-4/#valdef-max-lines-integer)
- [`<length>`](https://drafts.csswg.org/css-page-3/#valdef-page-size-length)
- [`<length>`](https://drafts.csswg.org/css-page-3/#valdef-page-bleed-length)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-scroll-snap-1/#valdef-scroll-padding-length-percentage-0)
- [`<color>`](https://drafts.csswg.org/css-scrollbars-1/#valdef-scrollbar-color-color)
- [`<string>`](https://drafts.csswg.org/css-shapes-1/#valdef-path-string)
- [`<image>`](https://drafts.csswg.org/css-shapes-1/#valdef-shape-outside-image)
- [`<number>`](https://drafts.csswg.org/css-shapes-1/#valdef-shape-image-threshold-number)
- [`<length-percentage>`](https://drafts.csswg.org/css-shapes-1/#valdef-shape-margin-length-percentage)
- [`<length-percentage [0,∞]>`](https://drafts.csswg.org/css-sizing-3/#valdef-width-length-percentage-0)
- [`<ratio>`](https://drafts.csswg.org/css-sizing-4/#valdef-aspect-ratio-ratio)
- [`<length>`](https://drafts.csswg.org/css-sizing-4/#valdef-contain-intrinsic-width-length)
- [`<number>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-balance-number)
- [`<time>`](https://drafts.csswg.org/css-speech-1/#valdef-pause-before-time)
- [`<time>`](https://drafts.csswg.org/css-speech-1/#valdef-rest-before-time)
- [`<uri>`](https://drafts.csswg.org/css-speech-1/#valdef-cue-before-uri)
- [`<family-name>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-family-family-name)
- [`<integer>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-family-integer)
- [`<percentage>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-rate-percentage)
- [`<frequency>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-pitch-frequency)
- [`<percentage>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-pitch-percentage)
- [`<percentage>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-range-percentage)
- [`<time>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-duration-time)
- [`<string>`](https://drafts.csswg.org/css-text-4/#valdef-hyphenate-character-string)
- [`<string>`](https://drafts.csswg.org/css-text-4/#valdef-text-align-string)
- [`<string>`](https://drafts.csswg.org/css-text-decor-3/#valdef-text-emphasis-style-string)
- [`<length>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-thickness-length)
- [`<percentage>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-thickness-percentage)
- [`<length>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-underline-offset-length)
- [`<percentage>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-underline-offset-percentage)
- [`<length>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-skip-inset-length)
- [`<string>`](https://drafts.csswg.org/css-text-decor-4/#valdef-text-emphasis-style-string)
- [`<length [0,∞]>`](https://drafts.csswg.org/css-transforms-2/#valdef-perspective-length-0)
- [`<percentage>`](https://drafts.csswg.org/css-transforms-2/#valdef-perspective-origin-percentage)
- [`<length>`](https://drafts.csswg.org/css-transforms-2/#valdef-perspective-origin-length)
- [`<color>`](https://drafts.csswg.org/css-ui-4/#valdef-accent-color-color)
- [`<custom-ident>`](https://drafts.csswg.org/css-will-change-1/#valdef-will-change-custom-ident)
- [`<number>`](https://drafts.fxtf.org/fill-stroke-3/#valdef-stroke-miterlimit-number)
- [`<angle>`](https://drafts.fxtf.org/motion-1/#valdef-ray-angle)

Public dfns with a `dfn` type:
- [`East Asian width property`](https://drafts.csswg.org/css-text-3/#unicode-east-asian-width)
- [`general category`](https://drafts.csswg.org/css-text-3/#unicode-general-category)
- [`script property`](https://drafts.csswg.org/css-text-3/#unicode-script)
- [`Vertical Orientation`](https://drafts.csswg.org/css-text-3/#unicode-vertical-orientation)
- [`East Asian width property`](https://drafts.csswg.org/css-text-4/#unicode-east-asian-width)
- [`general category`](https://drafts.csswg.org/css-text-4/#unicode-general-category)
- [`script property`](https://drafts.csswg.org/css-text-4/#unicode-script)
- [`Vertical Orientation`](https://drafts.csswg.org/css-text-4/#unicode-vertical-orientation)
- [`indexed property getter`](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericarray-indexed-property-getter)
- [`indexed property getter`](https://immersive-web.github.io/webxr/#xrinputsourcearray-indexed-property-getter)

**Comment by dontcallmedom** [comment]
great, thanks for the detailed analysis, and let's merge this then :)

**Pull request merged**
